#!/usr/bin/env bash

set -e

# TODO change to yabairc
brew tap crisidev/homebrew-chunkwm
brew tap mopidy/mopidy
brew update

PACKAGES=(
  --with-logging koekeishiya/formulae/skhd
  --with-tmp-logging chunkwm
  reattach-to-user-namespace
  ag
  ripgrep
  ranger
  openconnect
  zsh
  lnav # Log viewer
  tig
  exa # ls replacement
  thefuck
  --HEAD universal-ctags/universal-ctags/universal-ctags
  mopidy
  mopidy-spotify
  ncmpcpp
  pipx
)

CASKS=(
  amethyst
)

brew install "${PACKAGES[@]}"
brew cleanup
brew cask install "${CASKS[@]}"
brew cask cleanup

# Manual:
# - https://github.com/erroneousboat/slack-term

# Show filename extensions by default
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# Show all files by default
defaults write com.apple.Finder AppleShowAllFiles true

# Because of Apple... $#$#$#" Comment path_helper script in /etc/zprofile

# disable bouncing Dock icons (except Launchpad) for this account
defaults write com.apple.dock no-bouncing -bool True
killall Dock
