#!/usr/bin/env bash

set -e

sudo apt install \
   xsel unrar p7zip \
   zsh silversearcher-ag colordiff colormake \
   ranger atool caca-utils highlight libsixel-bin \
   redshift \
   mosh zathura mupdf htop \
   vlc ffmpeg synaptic \
   python-virtualenv

# FS for Android usb mounting
sudo apt install  mtpfs
# wajig large -> list all installed and size
sudo apt install wajig
# Autocompletion of words. Used with vim.
sudo apt install look
# Samba printer client
sudo apt install smbclient

pip install --user \
  virtualenvwrapper
pip3 install --user \
  neovim neovim-remote
# For vim ultisnips
pip3 install --user \
  unidecode

kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true

kwin_x11 --replace & disown
