#
# User configuration sourced by interactive shells
#

function source_file() {
    if [[ -r $1 ]]; then
        source $1
    fi
}

# Base setup
source ${ZDOTDIR:-${HOME}}/.zim/init.zsh

# Utility tools
export NVM_DIR="$HOME/.nvm"
export WORKON_HOME=$HOME/.virtualenvs
export SDKMAN_DIR="$HOME/.sdkman"
source_file "$NVM_DIR/nvm.sh"
source_file '~/.local/bin/virtualenvwrapper.sh' # Use _lazy
source_file '~/.sdkman/bin/sdkman-init.sh'
source ~/.fzf.zsh
source ~/.zplug/init.zsh

# Plugins
# TODO https://github.com/mssun/dotfiles/blob/master/.zshrc.zplug
# zplug manage itself like other packages: zplug update
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

zplug "zsh-users/zsh-completions"
zplug "gradle/gradle-completion"
zplug load #--verbose

# Custom settings
source $ZDOTFILES/user/funcs.zsh
source $ZDOTFILES/user/defaults.zsh
source $ZDOTFILES/user/tweaks.zsh
source $ZDOTFILES/user/keybindings.zsh
if [ -z ${LINUX+x} ]; then
    source $ZDOTFILES/user/linux.zsh
fi

export GRADLE_OPTS=-Dorg.gradle.daemon=true

# Mac java change default version
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
export JAVA_7_HOME=$(/usr/libexec/java_home -v1.7)

alias java7='export JAVA_HOME=$JAVA_7_HOME'
alias java8='export JAVA_HOME=$JAVA_8_HOME'

#default java8
export JAVA_HOME=$JAVA_8_HOME

